set(SDL2_DISABLE_INSTALL
    ON
    CACHE BOOL "" FORCE)
set(SDL2_DISABLE_UNINSTALL
    ON
    CACHE BOOL "" FORCE)
set(SDL2_DISABLE_MAIN
    ON
    CACHE BOOL "" FORCE)
set(SDL2_SHARED
    ON
    CACHE BOOL "" FORCE)
set(SDL2_STATIC
    OFF
    CACHE BOOL "" FORCE)
add_subdirectory("${PONG_DEPENDENCIES_DIR}/SDL-2.28.x"
                 "${PONG_DEPENDENCIES_BUILD_DIR}/SDL2")

set_target_properties(
  SDL2 PROPERTIES ARCHIVE_OUTPUT_DIRECTORY "${PONG_DEPENDENCIES_LIB_DIR}"
                  LIBRARY_OUTPUT_DIRECTORY "${PONG_DEPENDENCIES_LIB_DIR}")
